// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyv8gMx_mQijG7-lgc9ARGkDPrgSw8Gtg',
    appId: '1:752510112603:web:b8727c6b574615469cc07e',
    messagingSenderId: '752510112603',
    projectId: 'clothingstore-a6007',
    authDomain: 'clothingstore-a6007.firebaseapp.com',
    storageBucket: 'clothingstore-a6007.firebasestorage.app',
    measurementId: 'G-JY6QJCK6D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7O-JfRz6YmxQzM6hK7l6ZLPYyzOES0iA',
    appId: '1:752510112603:android:2cad2f7e46a104ad9cc07e',
    messagingSenderId: '752510112603',
    projectId: 'clothingstore-a6007',
    storageBucket: 'clothingstore-a6007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDve_ZDwmq0Jnh_ie0qAZ3FByGk2RtguYc',
    appId: '1:752510112603:ios:b4a9fdc863d286219cc07e',
    messagingSenderId: '752510112603',
    projectId: 'clothingstore-a6007',
    storageBucket: 'clothingstore-a6007.firebasestorage.app',
    iosBundleId: 'com.example.clothingStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDve_ZDwmq0Jnh_ie0qAZ3FByGk2RtguYc',
    appId: '1:752510112603:ios:b4a9fdc863d286219cc07e',
    messagingSenderId: '752510112603',
    projectId: 'clothingstore-a6007',
    storageBucket: 'clothingstore-a6007.firebasestorage.app',
    iosBundleId: 'com.example.clothingStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyv8gMx_mQijG7-lgc9ARGkDPrgSw8Gtg',
    appId: '1:752510112603:web:3a463886edffb8509cc07e',
    messagingSenderId: '752510112603',
    projectId: 'clothingstore-a6007',
    authDomain: 'clothingstore-a6007.firebaseapp.com',
    storageBucket: 'clothingstore-a6007.firebasestorage.app',
    measurementId: 'G-TPNHC536XG',
  );
}
